### ISSUE TITLE
Mixin updating the mongoDB row with the last csv item. 

### ISSUE THREAD

**Issue by nicofx** [jonathan-casarrubias/loopback-import-mixin#9]
Hi Guys, 

I´m trying to implement the mixin in a project and everything works as expected with a detail:
only is inserted the last row of my csv.
Checked and double checked the csv format and seems to be ok. Also the mapping configuration.

Am I missing something which causes the import process to only add (in fact update) the last item of my csv?

I´m using Loopback 3 and MongoDB as datasource for the model I´m working with. My testing csv has 30 rows.

Thanks on advance and Cheers, 
Nico

**Comment by jonathan-casarrubias** [comment]
Hi  nicofx thanks for reaching out, hey so what are you using for PK? It seems the PK might be the same in each row, therefore is updating instead of inserting a new row

**Comment by nicofx** [comment]
Thanks Johathan! I messed up with different names for the PK and the name in the csv. It is working like a charm!
Mil Gracias!!
